# Generated by Django 5.1 on 2024-10-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="department",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
