# Generated by Django 5.1.2 on 2024-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_adminwhitelist_adminrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwhitelist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
