# Generated by Django 5.1 on 2024-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_attendee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="is_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendee",
            name="present_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
