# Generated by Django 5.1.2 on 2024-10-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_attendee_is_present_attendee_present_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='qr_code_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
