# Generated by Django 5.1.2 on 2024-11-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_adminwhitelist_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
