# Generated by Django 5.1.2 on 2024-11-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_adminuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
    ]
