# Generated by Django 5.1.2 on 2024-10-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_attendee_qr_code_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='qr_code_image_url',
        ),
    ]
