# Generated by Django 5.1.2 on 2024-10-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_attendee_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='sub_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
