# Generated by Django 5.1.2 on 2024-11-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_adminuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRequest',
        ),
    ]
