# Generated by Django 5.1.2 on 2024-10-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_attendee_sub_department_alter_attendee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
