# Generated by Django 5.1.2 on 2025-01-16 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_adminwhitelist_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('number_of_attendees', models.IntegerField(default=0)),
                ('group_facilitator', models.CharField(max_length=255)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='assigned_events',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='registration.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.event'),
        ),
    ]
