# Generated by Django 5.1.2 on 2024-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_attendee_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='scan_status',
            field=models.BooleanField(default=False),
        ),
    ]
