# Generated by Django 5.1.2 on 2025-01-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_event_adminuser_assigned_events_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='assigned_events',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
