# Generated by Django 5.1.2 on 2024-10-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_attendee_scan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='scan_status',
        ),
    ]
