# Generated by Django 5.1.2 on 2025-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_admin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='assigned_events',
            field=models.ManyToManyField(blank=True, related_name='assigned_admins', to='registration.event'),
        ),
    ]
