# Generated by Django 5.1.2 on 2025-01-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_event_assigned_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_admin',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
