# Generated by Django 5.1.2 on 2025-01-17 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_event_assigned_admin'),
    ]

    def get_default_admin():
        # Add your logic to fetch the default admin
        # For example, if you're assigning the first admin by email, use this:
        return settings.AUTH_USER_MODEL.objects.get(email='admin@example.com')

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_admin',
            field=models.ForeignKey(
                blank=True,
                default=get_default_admin,  # Use the function you defined above
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
