# Generated by Django 5.1.2 on 2025-01-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_event_assigned_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='assigned_events',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
