# Generated by Django 5.1.2 on 2025-01-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
    ]
