# Generated by Django 5.1.2 on 2025-01-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facilitator',
        ),
    ]
