# Generated by Django 5.1.2 on 2025-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_remove_event_facilitator'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='templates/')),
            ],
        ),
    ]
