# Generated by Django 5.1.2 on 2025-02-05 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_qrtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtemplate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
