# Generated by Django 5.1.2 on 2025-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_mealclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealclaim',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='mealclaim',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mealclaim',
            name='breakfast_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealclaim',
            name='dinner_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealclaim',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mealclaim',
            name='lunch_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
