# Generated by Django 5.1.2 on 2025-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_alter_attendee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
    ]
